name: gwm
description: Git Worktree Manager - Streamlined Git worktree management
version: 0.1.1

environment:
  sdk: ^3.10.4

dependencies:
  args: ^2.7.0
  glob: ^2.1.3
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  lints: ^6.0.0
  mocktail: ^1.0.4
  test: ^1.25.6
