name: gwt
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  glob: ^2.1.3
  path: ^1.9.1
  process_runner: ^4.2.4
  yaml: ^3.1.3

dev_dependencies:
  build_runner: ^2.10.4
  lints: ^6.0.0
  mockito: ^5.6.1
  test: ^1.25.6
